var INICIO = 4;
var GESAD_CONFERIR_PRECADASTRO = 5;
var AUTO_APROVADO = 7;
var FIM = 9;
var NOTIFICAR_GECON_PARA_COMPLEMENTO_DE_CADASTRO = 11;
var APROVACAO_GECON = 13;
var FIM = 15;
var CORRIGIR_INFORMACOES = 52;
